export const components = [
  { text: 'Foo 组件示例', link: '/components/foo' },
  { text: 'Button 按钮', link: '/components/button' },
  { text: 'Icon 图标', link: '/components/icon' },
  { text: 'Menu 导航菜单', link: '/components/menu' },
  { text: 'MenuItem 导航菜单子元素', link: '/components/menu-item' },
  { text: 'Form 表单', link: '/components/form' },
  { text: 'FormItem 表单项', link: '/components/form-item' },
  { text: 'Input 输入框', link: '/components/input' },
  { text: 'Col 列', link: '/components/col' },
  { text: 'SubMenu 下拉菜单', link: '/components/sub-menu' },
  { text: 'Datepicker 日期选择框', link: '/components/datepicker' },
  { text: 'Alert 警告', link: '/components/alert' },
  { text: 'Switch 选择器', link: '/components/switch' },
  { text: 'Avatar 头像', link: '/components/avatar' },
  { text: 'Row 行', link: '/components/row' },
  { text: 'Empty 空状态', link: '/components/empty' },
  { text: 'Card 卡片', link: '/components/card' },
  { text: 'Progress 进度展示', link: '/components/progress' },
  { text: 'Drawer 抽屉', link: '/components/drawer' },
  { text: 'Empty 空状态', link: '/components/empty' },
  { text: 'Card 卡片', link: '/components/card' },
  { text: 'Progress 进度展示', link: '/components/progress' },
  { text: 'Message 消息', link: '/components/message' },
  { text: 'Link 链接', link: '/components/link' },
  { text: 'Table 表格', link: '/components/table' },
  { text: 'BackToTop 回到顶部', link: '/components/back-to-top' }
] // end
