name: Deploy to server

on:
  push:
    branches:
      - main # 可以根据实际需要修改

jobs:
  deploy:
    runs-on: ubuntu-latest # 可以根据实际需要修改
    steps:
      - name: 检查代码
        uses: actions/checkout@v2
      - name: 使用Pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.14.2
      - name: 安装依赖
        run: pnpm install
      - name: 打包部署文件
        run: pnpm run docs:build
      - name: 将dist文件复制在linux文件夹
        run: |
          mkdir -p dist
          cp -R docs/.vitepress/dist/* dist/
      - name: 向服务器上传文件
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: dist/
          target: /www/wwwroot/hareui.snowhouse.space