name: Deploy to server

on:
  push:
    branches:
      - main # 可以根据实际需要修改

jobs:
  deploy:
    runs-on: ubuntu-latest # 可以根据实际需要修改
    steps:
      - name: 检查代码
        uses: actions/checkout@v2
      - name: 使用Pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.14.2
      - name: 安装依赖
        run: pnpm install
      - name: 打包部署文件
        run: pnpm run docs:build
      - name: 向服务器上传文件
        run: scp -r -i ${{ secrets.SERVER_KEY }} ${{ github.workspace }}/docs/.vitepress/dist ${{ SERVER_USERNAME }}@${{ SERVER_HOST }}:/www/wwwroot/hareui.snowhouse.space
